import { Inter } from "next/font/google";
import { Montserrat,Poppins } from 'next/font/google'

import "./globals.css";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--primary-font",
  weight:['700']
})

const poppins = Poppins({
  subsets: ['latin'],
  variable: "--secondary-font",
  weight:'900'
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${poppins.variable}`}>{children}</body>
    </html>
  );
}
